apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: default
spec:
  ports:
    - port: 2181
      protocol: TCP
      targetPort: 2181
  selector:
    run: zookeeper
  type: LoadBalancer
