apiVersion: v1
kind: Pod
metadata:
  name: zookeeper
  labels:
    app: zooApp
spec:
  hostname: zookeeper
  containers:
    - name: zooker-container
      image: confluentinc/cp-zookeeper:6.0.0
      imagePullPolicy: IfNotPresent      
      env:
      - name: ZOOKEEPER_CLIENT_PORT
        value: "2181"
      - name: ZOOKEEPER_TICK_TIME
        value: "2000"
      ports:
        - containerPort: 2181
          name: "zoo"

