apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-pub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pub
  template:
    metadata:
      labels:
        app: pub
    spec:
      containers:
      - name: pub
        image: gcr.io/mchirico/gopub:test
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
