apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-sub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sub
  template:
    metadata:
      labels:
        app: sub
    spec:
      containers:
      - name: sub
        image: gcr.io/mchirico/readtemp:test
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
